language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2

install:
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    
script:
    # grep so that download counts don't appear in log files
    - if [ ! -d $HOME/.m2/repository/org/spigotmc/spigot/1.12.2-R0.1-SNAPSHOT/ ]; then echo "Spigot build not found, running BuildTools."; java -jar BuildTools.jar --rev 1.12.2; fi;
    - mvn verify
    
before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

after_success:
  - chmod +x success.sh
  - ./success.sh
after_failure:
  - chmod +x fail.sh
  - ./fail.sh
