language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
  - ELLIRION_UTIL_PATH="~/EllirionUtilDeploy"

install:
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    
script:
    # grep so that download counts don't appear in log files
    - if [ ! -d $HOME/.m2/repository/org/spigotmc/spigot/1.16.3-R0.1-SNAPSHOT/ ]; then echo "Spigot build not found, running BuildTools."; java -jar BuildTools.jar --rev 1.16.3; fi;
    - git clone https://ellirionstudios@gmail.com:AXGzfE53Mef7KJ82b@github.com:OldaranT/EllirionUtil.git --single-branch --branch develop ${ELLIRION_UTIL_PATH}
  #    - echo "<settings><servers><server><id>jitpack.io</id><username>\${env.JITPACK_AUTH}</username><password>.</password></server></servers></settings>" > $HOME/.m2/settings.xml
    - mvn verify
    
before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

after_success:
  - chmod +x success.sh
  - ./success.sh
after_failure:
  - chmod +x fail.sh
  - ./fail.sh
