name: EllirionCore
main: com.ellirion.core.EllirionCore
version: 0.0.1
description: EllirionCore
authors: [OldaranT, Nick Kronenberg]
load: POSTWORLD
commands:
  CreateRace:
      description: Create a race and usage the plot your standing on as homeplot.
      usage: /createRace <race name> <color>
      aliases: [cr, race-create]
      permission: ellirion.core.race.createrace
      permission-message: §4You do not have permission for this command!§r
  JoinRace:
      description: Join a race by standing on a race owned plot.
      usage: /joinRace, /jr
      aliases: [jr, race-join]
      permission: ellirion.core.race.joinrace
      permission-message: §4You do not have permission for this command!§r
  RemoveRace:
      description: Removes race by name.
      usage: /rr <raceName>
      aliases: [rr, race-remove]
      permission: ellirion.core.race.removerace
      permission-message: §4You do not have permission for this command!§r
  CreatePlots:
      description: Create plots
      usage: /cps <PLOT-SIZE> <MAP-RADIUS> <CENTER-X> <CENTER-Z>
      aliases: [cps, plot-create]
      permission: ellirion.core.plot.createplots
      permission-message: §4You do not have permission for this command!§r
  GetPlot:
      description: Get plot from location
      usage: /GetPlot, /gp
      aliases: [gp, plot-get]
      permission: ellirion.core.plot.getplot
      permission-message: §4You do not have permission for this command!§r
  TeleportToPlot:
      description: Teleport player to selected plot.
      usage: /TeleportToPlot <X> <Z>, /ttp <X> <Z>
      aliases: [ttp, plot-teleport]
      permission: ellirion.core.plot.teleporttoplot
      permission-message: §4You do not have permission for this command!§r
  ClaimPlot:
      description: Claim a plot for your race by coords or location of the player.
      usage: /cp <X> <Y> or /cp (Takes plot of player location)
      aliases: [cp, plot-claim]
      permission: ellirion.core.plot.claimplot
      permission-message: §4You do not have permission for this command!§r
  PlotMap:
      description: Get a map of surrounding plots.
      usage: /PlotMap
      aliases: [plot-map]
      permission: ellirion.core.plot.plotmap
      permission-message: §4You do not have permission for this command!§r
  AssignTradingCenter:
      description: Assign trading center to be the owner of a plot
      usage: /AssignTradingCenter [<X> <Z>]
      aliases: [plot-atc]
      permission: ellirion.core.plot.assigntradingcenter
      permission-message: §4You do not have permission for this command!§r
  BeginGamemode:
      description: Begin creating a gamemode.
      usage: /begingamemode <GameName>
      aliases: [game-begin]
      permission: ellirion.core.game.begingamemode
      permission-message: §4You do not have permission for this command!§r
  GameState:
      description: Get the current game state.
      usage: /gamestate
      aliases: [game-state]
      permission: ellirion.core.game.gamestate
      permission-message: §4You do not have permission for this command!§r
  NextStep:
      description: Advance the gamemode to the next setup step.
      usage: /NextStep
      aliases: [game-nextstep]
      permission: ellirion.core.game.nextstep
      permission-message: §4You do not have permission for this command!§r
  LoadGame:
      description: Load the game from the database by name
      usage: /LoadGame <GameName>
      aliases: [game-load]
      permission: ellirion.core.game.loadgame
      permission-message: §4You do not have permission for this command!§r
  UnloadGame:
      description: Unload the game from the database by name
      usage: /UnloadGame <GameName>
      aliases: [game-unload]
      permission: ellirion.core.game.unloadgame
      permission-message: §4You do not have permission for this command!§r
  ConfirmGamemode:
      description: Confirm the gamemode and start saving configuration.
      usage: /confirmgamemode while on the last step of the setu
      aliases: [game-confirm]
      permission: ellirion.core.game.confirmgamemode
      permission-message: §4You do not have permission for this command!§r
  CancelSetup:
      description: Cancel the gamemode setup.
      usage: /cancelsetup during the gamemode setup phase
      aliases: [game-cancel]
      permission: ellirion.core.game.cancelsetup
  CreateGroundWar:
      description: create a ground war
      usage: /creategroundwar
      aliases: [war-create]
      permission: ellirion.core.war.creategroundwar
      permission-message: §4You do not have permission for this command!§r
  WagerPlot:
      description: wager a plot in your ground war
      usage: /wagerplot [<plot-x> <plot-z>]
      aliases: [war-wagerplot]
      permission: ellirion.core.war.wagerplot
      permission-message: §4You do not have permission for this command!§r
  GetGroundwar:
      description: Get the details of a grouns war
      usage: /getgroundwar
      aliases: [war-get]
      permission: ellirion.core.war.getgroundwar
      permission-message: §4You do not have permission for this command!§r
  ConfirmGroundWar:
      description: confirm ground war
      usage: /confirmgroundwar
      aliases: [war-confirm]
      permission: ellirion.core.war.confirmgroundwar
      permission-message: §4You do not have permission for this command!§r
  JoinGroundWar:
      description: join a groundwar
      usage: /joingroundwar
      aliases: [war-join]
      permission: ellirion.core.war.joingroundwar
      permission-message: §4You do not have permission for this command!§r
  LeaveGroundWar:
      description: Leave the ground war you're in.
      usage: /leavegroundwar
      aliases: [war-leave]
      permission: ellirion.core.war.leavegroundwar
      permission-message: §4You do not have permission for this command!§r
  CancelGroundWar:
      description: Cancel the ground war you created.
      usage: /cancelgroundwar
      aliases: [war-cancel]
      permission: ellirion.core.war.cancelgroundwar
      permission-message: §4You do not have permission for this command!§r
depend: [EllirionUtil]