name: EllirionCore
main: com.ellirion.core.EllirionCore
version: 0.0.1
description: introduction
commands:
  createRace:
      description: allows the server to create a race. players are not allowed to do this.
      usage: createRace <race name> <color>