name: EllirionCore
main: com.ellirion.core.EllirionCore
version: 0.0.1
description: EllirionCore
authors: [OldaranT, Nick Kronenberg]
load: POSTWORLD
commands:
  createRace:
      description: allows the server to create a race. players are not allowed to do this.
      usage: /createRace <race name> <color>
      aliases: [cr]
  joinRace:
      description: joins a race.
      usage: /joinRace /jr
      aliases: [jr]
  CreatePlots:
      description: Create plots
      usage: /cps <PLOT-SIZE> <MAP-RADIUS> <CENTER-X> <CENTER-Z>
      aliases: [cps]
  GetPlot:
      description: Get plot from location
      usage: /gp
      aliases: [gp]
  TeleportToPlot:
      description: Teleport player to selected plot.
      usage: /ttp <X> <Y>
      aliases: [ttp]
  ClaimPlot:
      description: Claim a plot for your race
      usage: /cp <X> <Y> or /cp (Takes plot of player location)
      aliases: [cp]
  RemoveRace:
      Description: Removes the specified race.
      usage: /rr <raceName>
      aliases: [rr]
  BeginGamemode:
      Description: Begin creating a gamemode.
      usage: /begingamemode
  GameState:
      Description: Get the current game state.
      usage: /gamestate
depend: [EllirionUtil]