name: EllirionCore
main: com.ellirion.core.EllirionCore
version: 0.0.1
description: EllirionCore
authors: [OldaranT, Nick Kronenberg]
commands:
  createRace:
      description: allows the server to create a race. players are not allowed to do this.
      usage: createRace <race name> <color>
      aliases: [cr]
  joinRace:
      description: joins a race.
      usage: /joinRace <race name>
      aliases: [jr]
  CreatePlots:
      description: Create plots
      usage: /cp <PLOT-SIZE> <MAP-RADIUS> <CENTER-X> <CENTER-Z>
      aliases: [cp]
  GetPlot:
      description: Get plot from location
      usage: /gp
      aliases: [gp]
  SetOwner:
      Description: Set the owner of the plot
      usage: /so
      aliases: [so]
  TeleportToPlot:
      Description: Teleport player to selected plot.
      usage: /ttp <X> <Y>
      aliases: [ttp]
